spring.application.name=shoppingapp
spring.datasource.url=jdbc:mysql://localhost:3306/shoppingdb
spring.datasource.username=root
spring.datasource.password=Kahtap_8020
 
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true