spring.application.name=shoppingapp
spring.datasource.url=jdbc:mysql://localhost:3306/bathinanna
spring.datasource.username=root
spring.datasource.password=Nanna@9618
 
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true